b2b_project/api/shop/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from .views import (BrandViewSet, 
                    CategoryViewSet, 
                    SubCategoryViewSet, 
                    SubSubCategoryViewSet, 
                    ProductViewSet)

router = SimpleRouter()
router.register('category', CategoryViewSet)
router.register('sub-category', SubCategoryViewSet)
router.register('sub-sub-category', SubSubCategoryViewSet)
router.register('brand', BrandViewSet)
router.register('', ProductViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

b2b_project/api/urls.py
from django.urls import path, include

urlpatterns = [
    path('users/', include('user.urls')),
    path('products/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
]

b2b_project/b2b_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('accounts/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
    #path('api/', include('api.urls')),
    path('', include('dashboard.urls')),
    path('', include('shop.urls')),
    path('', include('orders.urls')),
    path('', include('accounting.urls')),
    path('', include('hrm.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

b2b_project/shop/urls.py
from django.urls import path

from . import views


app_name = 'shop'

urlpatterns = [ 
    path('', views.home, name = 'home'),
    path('admin-dashboard/', views.admin_dashboard, name = 'admin_dashboard'),
    path('admin-dashboard/profile/', views.admin_profile, name = 'admin_profile'),
    path('admin-dashboard/profile/<str:edit>/', views.admin_profile, name = 'admin_profile_edit'),
    path('admin-dashboard/product-list/', views.product_list, name = 'product_list'),
    path('admin-dashboard/product/<int:id>/', views.product_detail, name = 'product_detail'),
    path('admin-dashboard/add-product/', views.add_product, name = 'add_product'),
    path('admin-dashboard/customer-list/', views.list_customer, name = 'customer_list'),
    path('admin-dashboard/customer-list/<int:user_id>/block/', views.block_customer, name = 'block_customer'),
    path('admin-dashboard/customer-requests/', views.customer_requests, name = 'customer_requests'),
    path('admin-dashboard/customer-requests/<int:user_id>/remove/', views.remove_customer, name = 'remove_customer'),
    path('admin-dashboard/customer-requests/<int:user_id>/approve/', views.approve_customer, name = 'approve_customer'),
    path('admin-dashboard/salesman-list/', views.list_salesman, name = 'salesman_list'),
    path('admin-dashboard/salesman-requests/', views.salesman_requests, name = 'salesman_requests'),
    path('admin-dashboard/salesman-requests/<int:user_id>/remove/', views.remove_salesman, name = 'remove_salesman'),
    path('admin-dashboard/salesman-requests/<int:user_id>/approve/', views.approve_salesman, name = 'approve_salesman'),
    path('admin-dashboard/customer-list/<int:user_id>/block/', views.block_salesman, name = 'block_salesman'),
]

b2b_project/hrm/models.py
from django.db import models
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField


class Department(models.Model):
    name = models.CharField(max_length = 150)

    def __str__(self):
        return self.name


class Employee(models.Model):
    department = models.ForeignKey(Department, on_delete = models.CASCADE)
    full_name = models.CharField(max_length = 100)
    designation = models.CharField(max_length=50)
    salary = models.PositiveIntegerField()
    contact_no = PhoneNumberField(max_length = 15)
    email = models.EmailField()
    address = models.CharField(max_length = 100)
    joined_date = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.full_name

    def get_per_day_salary(self):
        return self.salary/24


class Date(models.Model):
    date = models.DateField(default=timezone.now, unique=True)

    def __str__(self):
        return self.date


class Attendance(models.Model):
    STATUS_CHOICES = (('absent','Absent'),('present','Present'))
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='attendance')
    date = models.ForeignKey(Date, related_name='attendance', on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS_CHOICES, max_length=15)
    first_in = models.TimeField(blank=True, null=True, default=timezone.now)
    last_out = models.TimeField(blank=True, null=True, default=timezone.now)

    #class Meta:
    #    unique_together = ('employee','date')

b2b_project/shop/forms.py
from django import forms
from django.db import transaction

from user.models import User, Admin, Salesman
from shop.models import Product

class AdminProfileEditform(forms.ModelForm): 
    class Meta:
        model = Admin
        fields = ['full_name', 'contact_no', 'address']

class AddProductForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['category'].widget.attrs.update({'class': 'form-select'})
        self.fields['sub_category'].widget.attrs.update({'class': 'form-select'})
        self.fields['sub_sub_category'].widget.attrs.update({'class': 'form-select'})
        self.fields['brand'].widget.attrs.update({'class': 'form-select'})
        self.fields['image'].widget.attrs.update({'class': 'form-control'})
        self.fields['color'].widget.attrs.update({'class': 'form-select'})
        self.fields['price'].widget.attrs.update({'class': 'form-control'})
        self.fields['discounted_price'].widget.attrs.update({'class': 'form-control'})
        self.fields['stock'].widget.attrs.update({'class': 'form-control'})
        self.fields['size'].widget.attrs.update({'class': 'form-control'})
        self.fields['type'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Product
        fields = '__all__'

class AddSalesmanForm(forms.Form):

    class Meta:
        model = User
        fields = ['email','password']
    
    @transaction.atomic
    def save(self, request,):
        user = super(AddSalesmanForm, self).save()
        user.is_salesman = True
        user.save()
        salesman = Salesman(user = user, )
        return None

b2b_project/api/shop/views.py
from unicodedata import category
from rest_framework.viewsets import ModelViewSet

from .permissions import IsAdminOrReadOnly
from .serializers import (CategorySerializer,
                        SubCategorySerializer, 
                        SubSubCategorySerializer, 
                        ProductSerializer,
                        BrandSerializer)
from .models import Category, SubCategory, SubSubCategory, Product, Brand

class CategoryViewSet(ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [IsAdminOrReadOnly]

class SubCategoryViewSet(ModelViewSet):
    queryset = SubCategory.objects.all()
    serializer_class = SubCategorySerializer
    permission_classes = [IsAdminOrReadOnly]

class SubSubCategoryViewSet(ModelViewSet):
    queryset = SubSubCategory.objects.all()
    serializer_class = SubSubCategorySerializer
    permission_classes = [IsAdminOrReadOnly]

class ProductViewSet(ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = [IsAdminOrReadOnly]

class BrandViewSet(ModelViewSet):
    queryset = Brand.objects.all()
    serializer_class = BrandSerializer
    permission_classes = [IsAdminOrReadOnly]

b2b_project/shop/views.py
import math
from datetime import timedelta, date
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from allauth.account.forms import ChangePasswordForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from orders.models import Order
from user.models import User
from .models import Product
from .decorators import admin_required
from .forms import AdminProfileEditform, AddProductForm
from .utils import (get_customer_report, 
                    get_revenue_report,
                    get_sales_report,
                    get_top_selling_product)


def home(request):
    return render(request, 'shop/home.html')


@login_required
@admin_required
def admin_dashboard(request):
    end_date = date.today() + timedelta(days=1)
    #get total orders of desired date range 
    order_duration = request.GET.get('duration', '1')
    start_date = date.today() - timedelta(days = int(order_duration))
    order_count = Order.objects.filter(created__range=[start_date, end_date]).count()
    previous_order_count = Order.objects.filter(created__range = [start_date, date.today()]).count()
    
    if previous_order_count > 0:
        percent_change = (order_count-previous_order_count)/previous_order_count*100
    else:
        percent_change = None

    #get total orders of desired date range
    revenue_duration = request.GET.get('revenue_duration', '1')
    revenue_start_date = date.today() - timedelta(days = int(revenue_duration))
    revenue = Order.objects.all().get_revenue(revenue_start_date, end_date)
    previous_revenue = Order.objects.all().get_revenue(revenue_start_date, date.today())

    if previous_revenue > 0:
        revenue_percent_change = math.floor(((revenue-previous_revenue)/previous_revenue*100))
    else:
        revenue_percent_change = None
    
     #get total orders of desired date range
    customer_duration = request.GET.get('customer_duration','1')
    customer_start_date = date.today() - timedelta(int(customer_duration))
    customer_count = User.objects.filter(is_customer = True, date_joined__range=[customer_start_date, end_date]).count()
    previous_customer_count = User.objects.filter(is_customer = True, date_joined__range = [customer_start_date, date.today()]).count()

    if previous_customer_count > 0:
        customer_percent_change = (customer_count - previous_customer_count)/previous_customer_count*100
    else:
        customer_percent_change = None
    
    report_timeframe = int(request.GET.get('report',7))
    #get the visualized report of sales, customers and revenue using apexchart.js
    dates = list(get_sales_report(report_timeframe).keys())
    dates.reverse()
    revenue_report = list(get_revenue_report(report_timeframe).values())
    revenue_report.reverse()
    customer_report = list(get_customer_report(report_timeframe).values())
    customer_report.reverse()
    sales_report = list(get_sales_report(report_timeframe).values())
    sales_report.reverse()
    recent_orders = Order.objects.all()[:50]
    top_selling_timeframe = int(request.GET.get('timeframe',1))
    top_selling_products = get_top_selling_product(top_selling_timeframe)

    return render(request, 'shop/admin_dashboard.html', {'order_count':order_count,
                                                         'filter_order_by':int(order_duration),
                                                         'percent_change':percent_change,
                                                         'revenue':revenue,
                                                         'revenue_duration':int(revenue_duration),
                                                         'revenue_percent_change':revenue_percent_change,
                                                         'customer_count':customer_count,
                                                         'customer_duration':int(customer_duration),
                                                         'customer_percent_change':customer_percent_change,
                                                         'dates':dates,
                                                         'revenue_report':revenue_report,
                                                         'customer_report':customer_report,
                                                         'sales_report':sales_report,
                                                         'recent_orders':recent_orders,
                                                         'top_selling_products':top_selling_products,
                                                         'top_selling_timeframe':top_selling_timeframe,})


@login_required
@admin_required
def admin_profile(request, edit = None, change_password = None):
    change_password_form = ChangePasswordForm()
    if edit == 'edit':
        if request.method == 'POST':
            admin_edit_form = AdminProfileEditform(request.POST)

            if admin_edit_form.is_valid():
                request.user.admin.full_name = admin_edit_form.cleaned_data['full_name']
                request.user.admin.address = admin_edit_form.cleaned_data['address']
                request.user.admin.contact_no = admin_edit_form.cleaned_data['contact_no']
                request.user.admin.save()
                return redirect('shop:admin_profile')

    return render(request, 'shop/admin_profile.html', {'change_password_form':change_password_form})


@login_required
@admin_required
def product_list(request):
    products = Product.objects.all()
    page = request.GET.get('page', 1)
    per_page = request.GET.get('per_page',100)
    paginator = Paginator(products, per_page)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return render(request, 'shop/product_list.html', {'products':products})


@login_required
@admin_required
def add_product(request):
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('shop:product_list')
    else:
        form = AddProductForm()
    return render(request, 'shop/add_product.html', {'form':form})


@login_required
@admin_required
def product_detail(request, id):
    product = get_object_or_404(Product, id = 1)
    return render(request,'shop/product_detail.html', {'product':product})


@login_required
@admin_required
def list_customer(request):
    customers = User.objects.filter(is_customer = True, is_active = True)
    return render(request, 'shop/customer_list.html', {'customers':customers})


@login_required
@admin_required
def block_customer(request,user_id):
    customer = get_object_or_404(User, id = user_id)
    customer.is_active = False
    customer.save()
    return redirect('shop:customer_list')


@login_required
@admin_required
def customer_requests(request):
    customer_requests = User.objects.filter(is_customer = True, is_active = False)
    return render(request, 'shop/customer_requests.html', {'customer_requests':customer_requests})


@login_required
@admin_required
def approve_customer(request, user_id):
    customer = get_object_or_404(User, id = user_id)
    customer.is_active = True
    customer.save()
    return redirect('shop:customer_requests')


@login_required
@admin_required
def remove_customer(request, user_id):
    customer = get_object_or_404(User, id = user_id)
    customer.delete()
    return redirect('shop:customer_requests')


@login_required
@admin_required
def salesman_requests(request):
    salesman_requests = User.objects.filter(is_salesman = True, is_active = False)
    return render(request, 'shop/salesman_requests.html', {'salesman_requests':salesman_requests})


@login_required
@admin_required
def approve_salesman(request, user_id):
    customer = get_object_or_404(User, id = user_id)
    customer.is_active = True
    customer.save()
    return redirect('shop:salesman_requests')


@login_required
@admin_required
def remove_salesman(request, user_id):
    customer = get_object_or_404(User, id = user_id)
    customer.delete()
    return redirect('shop:salesman_requests')


@login_required
@admin_required
def list_salesman(request):
    salesmen = User.objects.filter(is_salesman = True, is_active = True)
    return render(request, 'shop/salesman_list.html', {'salesmen':salesmen})


@login_required
@admin_required
def block_salesman(request,user_id):
    salesman = get_object_or_404(User, id = user_id)
    salesman.is_active = False
    salesman.save()
    return redirect('shop:salesman_list')

b2b_project/shop/templates/shop/add_salesman.html
{% extends 'shop/admin_base.html' %}
{% load static %}

{% block main %}
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center py-4">
                <a href="/" class="logo d-flex align-items-center w-auto">
                  <img src="{% static 'shop/assets/img/logo.png' %}" alt="">
                  <span class="d-none d-lg-block">B2B</span>
                </a>
              </div><!-- End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Add Salesman</h5>
                    <p class="text-center small">Enter details to create salesman account</p>
                  </div>

                  <form class="row g-3 needs-validation" novalidate method="post" action = "{% url 'shop:add_salesman' %}" >
                    {% csrf_token %}
                    <div class="col-12">
                      <label for="yourName" class="form-label">Salesman Name</label>
                      <input type="text" class = "form-control" name="full_name" maxlength="100" required id="id_full_name">
                      <div class="invalid-feedback">Please, enter salesman name!</div>
                    </div>

                    <div class="col-12">
                      <label for="yourEmail" class="form-label">Salesman Email</label>
                      <input type="email" class = "form-control" name="email" placeholder="E-mail address" autocomplete="email" required id="id_email">
                      <div class="invalid-feedback">Please enter a valid Email adddress!</div>
                    </div>

                    <div class="col-12">
                      <label for="yourEmail" class="form-label">Contact</label>
                      <input type="tel" class = "form-control" name="contact_no" required id="id_contact_no">
                    </div>

                    <div class="col-12">
                      <label for="yourEmail" class="form-label">Address</label>
                      <input type="text" class = "form-control" name="address" maxlength="200" required id="id_address">
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Password</label>
                      <input type="password" class = "form-control" name="password1" placeholder="Password" autocomplete="new-password" required id="id_password1">
                      <div class="invalid-feedback">Please enter password</div>
                    </div>
                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Add Salesman</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>

      </section>

    </div>
{% endblock %}

b2b_project/shop/templates/shop/admin_profile.html
{% extends 'shop/admin_base.html' %}

{% block main %}
    <div class="pagetitle">
      <h1 style="text-align: center">Profile</h1>
    </div><!-- End Page Title -->

    <section class="section profile">
      <div class="row">
        <div class="col-xl-2">

        </div>

        <div class="col-xl-8">

          <div class="card" style="min-height: 70vh;">
            <div class="card-body pt-3">
              <!-- Bordered Tabs -->
              <ul class="nav nav-tabs nav-tabs-bordered">

                <li class="nav-item">
                  <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Edit Profile</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password">Change Password</button>
                </li>

              </ul>
              <div class="tab-content pt-2">

                <div class="tab-pane fade show active profile-overview" id="profile-overview">
                  <h5 class="card-title">Profile Details</h5>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label ">Full Name</div>
                    {% if request.user.admin.full_name %}
                    <div class="col-lg-9 col-md-8">{{request.user.admin.full_name}}</div>
                    {% else %}
                    <div class="col-lg-9 col-md-8">Not Available</div>
                    {% endif %}
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label ">Email</div>
                    <div class="col-lg-9 col-md-8">{{request.user.email}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Contact</div>
                    {% if request.user.admin.contact_no %}
                    <div class="col-lg-9 col-md-8">{{request.user.admin.contact_no}}</div>
                    {% else %}
                    <div class="col-lg-9 col-md-8">+977 1234567890</div>
                    {% endif %}
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Address</div>
                    {% if request.user.admin.address %}
                    <div class="col-lg-9 col-md-8">{{request.user.admin.address}}</div>
                    {% else %}
                    <div class="col-lg-9 col-md-8">Not Available</div>
                    {% endif %}
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Joined Date</div>
                    <div class="col-lg-9 col-md-8">{{request.user.date_joined}}</div>
                  </div>

                </div>

                <div class="tab-pane fade profile-edit pt-3" id="profile-edit">
                  <!-- Profile Edit Form -->
                  <form method="POST" action="{% url 'shop:admin_profile_edit' 'edit' %}">
                    {% csrf_token %}
                    <div class="row mb-3">
                      <label for="full_name" class="col-md-4 col-lg-3 col-form-label">Full Name</label>
                      <div class="col-md-8 col-lg-9">
                        <input type="text" class="form-control"name="full_name" value="{{request.user.admin.full_name}}" maxlength="100" required id="id_full_name">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="contact" class="col-md-4 col-lg-3 col-form-label">Contact No.</label>
                      <div class="col-md-8 col-lg-9">
                      <input type="tel" class = "form-control" name="contact_no" value="{{request.user.admin.contact_no}}" maxlength="128" required id="id_contact_no">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="address" class="col-md-4 col-lg-3 col-form-label">Address</label>
                      <div class="col-md-8 col-lg-9">
                        <input type="text" class="form-control" name="address" value="{{request.user.admin.address}}" maxlength="200" required id="id_address">
                      </div>
                    </div>

                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                  </form>

                </div>

                <div class="tab-pane fade pt-3" id="profile-settings">

                  <!-- Settings Form -->
                  <form>

                    <div class="row mb-3">
                      <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Email Notifications</label>
                      <div class="col-md-8 col-lg-9">
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="changesMade" checked>
                          <label class="form-check-label" for="changesMade">
                            Changes made to your account
                          </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="newProducts" checked>
                          <label class="form-check-label" for="newProducts">
                            Information on new products and services
                          </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="proOffers">
                          <label class="form-check-label" for="proOffers">
                            Marketing and promo offers
                          </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="securityNotify" checked disabled>
                          <label class="form-check-label" for="securityNotify">
                            Security alerts
                          </label>
                        </div>
                      </div>
                    </div>

                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                  </form><!-- End settings Form -->

                </div>

                <div class="tab-pane fade pt-3" id="profile-change-password">
                  <!-- Change Password Form -->
                  <form method="post" action="{% url 'account_change_password' %}">
                    {% csrf_token %}
                    <div class="row mb-3">
                      <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input type="password" class="form-control" name="oldpassword" placeholder="Current Password" autocomplete="current-password" required id="id_oldpassword">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">New Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input type="password" class="form-control" name="password1" placeholder="New Password" autocomplete="new-password" required id="id_password1">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="renewPassword" class="col-md-4 col-lg-3 col-form-label">Re-enter New Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input type="password" class="form-control" name="password2" placeholder="New Password (again)" required id="id_password2">
                      </div>
                    </div>

                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Change Password</button>
                    </div>
                  </form>
                  <!-- End Change Password Form -->

                </div>

              </div><!-- End Bordered Tabs -->

            </div>
          </div>

        </div>
        <div class="col-xl-2">

        </div>
      </div>
    </section>

  </main><!-- End #main -->
  {% endblock %}

b2b_project/shop/templates/shop/customer_requests.html
{% extends 'shop/admin_base.html' %}

{% block main %}
<div class="pagetitle">
    <h1>Customer Requests</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'shop:admin_dashboard' %}">Dashboard</a></li>
        <li class="breadcrumb-item">Customer Requests</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section">
    <div class="row">
      <div class="col-lg-12">

        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Customer Requests</h5>
            <!-- Table with stripped rows -->
            <table class="table datatable">
              <thead>
                <tr>
                  <th scope="col">ID</th>
                  <th scope="col">Full Name</th>
                  <th scope="col">Contact No</th>
                  <th scope="col">Address</th>
                  <th scope="col">Email</th>
                  <th scope="col">Joined Date</th>
                  <th scope="col">Approve Request</th>
                  <th scope="col">Remove Request</th>
                </tr>
              </thead>
              
              <tbody>
                {% for customer in customer_requests %}
                <tr>
                  <th scope="row">{{customer.customer.id}}</th>
                  <td><a href="#">{{customer.customer.full_name}}</a></td>
                  <td>{{customer.customer.contact_no}}</td>
                  <td>{{customer.customer.address}}</td>
                  <td>{{customer.email}}</td>
                  <td>{{customer.date_joined}}</td>
                  <td><a href="{% url 'shop:approve_customer' customer.id %}" onclick="return confirm('Are you sure?')">Approve</a></td>
                  <td><a href="{% url 'shop:remove_customer' customer.id %}" onclick="return confirm('Are you sure?')">Remove</a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>
  </section>
{% endblock %}