b2b_project/api/urls.py
from django.urls import path, include

urlpatterns = [
    path('users/', include('user.urls')),
    path('products/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
]

b2b_project/b2b_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('accounts/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
    #path('api/', include('api.urls')),
    path('', include('dashboard.urls')),
    path('', include('shop.urls')),
    path('', include('orders.urls')),
    path('', include('accounting.urls')),
    path('', include('hrm.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

b2b_project/hrm/urls.py
from django.urls import path

from . import views

app_name = 'hrm'
urlpatterns = [ 
    path('admin-dashboard/employees/', views.employee_list, name = 'employee_list'),
    path('admin-dashboard/employees/add/', views.add_employee, name = 'add_employee'),
    path('admin-dashboard/employees/delete/<int:id>/', views.delete_employee, name = 'delete_employee'),
    path('admin-dashboard/employees/attendance/', views.add_attendance, name = 'attendance'),
]

b2b_project/hrm/models.py
from django.db import models
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField


class Department(models.Model):
    name = models.CharField(max_length = 150)

    def __str__(self):
        return self.name


class Employee(models.Model):
    department = models.ForeignKey(Department, on_delete = models.CASCADE)
    full_name = models.CharField(max_length = 100)
    designation = models.CharField(max_length=50)
    salary = models.PositiveIntegerField()
    contact_no = PhoneNumberField(max_length = 15)
    email = models.EmailField()
    address = models.CharField(max_length = 100)
    joined_date = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.full_name

    def get_per_day_salary(self):
        return self.salary/24


class Date(models.Model):
    date = models.DateField(default=timezone.now, unique=True)

    def __str__(self):
        return self.date


class Attendance(models.Model):
    STATUS_CHOICES = (('absent','Absent'),('present','Present'))
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='attendance')
    date = models.ForeignKey(Date, related_name='attendance', on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS_CHOICES, max_length=15)
    first_in = models.TimeField(blank=True, null=True, default=timezone.now)
    last_out = models.TimeField(blank=True, null=True, default=timezone.now)

    #class Meta:
    #    unique_together = ('employee','date')

b2b_project/hrm/forms.py
from django import forms

from .models import Attendance, Employee


class AddEmployeeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['department'].widget.attrs.update({'class': 'form-select'})
        self.fields['full_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['designation'].widget.attrs.update({'class': 'form-control'})
        self.fields['salary'].widget.attrs.update({'class': 'form-control'})
        self.fields['contact_no'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Employee
        fields = ['department', 'full_name', 'designation', 'salary', 'contact_no', 'email', 'address']


class AttendanceForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['employee'].widget.attrs.update({'class': 'form-select'})
        #self.fields['date'].widget.attrs.update({'class': 'form-control'})
        self.fields['status'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_in'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_out'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Attendance
        fields = ('employee', 'status', 'first_in', 'last_out')

AttendanceFormset = forms.formset_factory(form=AttendanceForm, extra=Employee.objects.count())

b2b_project/hrm/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required

from shop.decorators import admin_required
from .forms import AddEmployeeForm, AttendanceFormset, AttendanceForm
from .models import Employee, Attendance, Date

@login_required
@admin_required
def employee_list(request):
    employee_list = Employee.objects.all()
    return render(request, 'hrm/employee_list.html', {'employee_list':employee_list})


@login_required
@admin_required
def add_employee(request):
    if request.method == 'POST':
        form = AddEmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('hrm:employee_list')
        else:
            return HttpResponse("Invalid Form")    
    else:
        form = AddEmployeeForm() 
    return render(request, 'hrm/add_employee.html', {'form':form})


@login_required
@admin_required
def delete_employee(request, employee_id):
    employee = get_object_or_404(Employee, id = employee_id)
    employee.delete()
    return redirect('hrm:employee_list')


@login_required
@admin_required
def add_attendance(request):
    employee_list = Employee.objects.all()
    if request.method == 'POST':
        date = Date.objects.create(date = request.POST['date'])
        date.save()
        for x in range(1,len(employee_list)+1):
            employee = employee_list[x-1]
            status = request.POST[f'option{x}']
            first_in = request.POST[f'in-time{x}']
            last_out = request.POST[f'in-time{x}']
            attendance = Attendance(date=date,
                                    employee=employee,
                                    status=status,
                                    first_in=first_in,
                                    last_out=last_out)
            attendance.save()

    return render(request, 'hrm/attendance.html', {'employee_list':employee_list})

b2b_project/hrm/templates/hrm/add_employee.html
{% extends 'shop/admin_base.html' %}

{% block main %}
<section class="section">
<div class="row">
    <div class="col-xl-2"></div>
    <div class="col-xl-8">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Add Employee</h5>

                <form method="post" action="{% url 'hrm:add_employee' %}" class="row g-3 needs-validation">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="row mb-3">
                        <label class="col-md-4 col-lg-3 form-label">{{field.label}}</label>
                        <div class="col-md-8 col-lg-9">
                        {{field}}
                        </div>
                    </div>
                    {% endfor %}
                    <div class="text-center">
                    <button type="submit" class="btn btn-success">Add Employee</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
    <div class="col-xl-2"></div>
</div>
</section>
{% endblock %}

b2b_project/hrm/templates/hrm/attendance.html
{% extends 'shop/admin_base.html' %}

{% block main %}

<section class="section">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title" style="float: left;">Employee Attendance</h5>
          <!-- 
          <h5 class="card-title" style="float: right;"><a href="{% url 'hrm:add_employee' %}"
              class="btn btn-success">View Attendances</a></h5>-->
        </div>
        <div class="card-body">
          <form method="post" action="#">
            <br>
            <div class="float-start">
              <input type="date" name="date" class="form-control">
            </div>
            <br>
            <br>
            <table class="table align-middle mb-0 bg-white ">
              <thead class="bg-light">
                <tr>
                  <th>Employee</th>
                  <th>Status</th>
                  <th>First IN</th>
                  <th>Last Out</th>
                </tr>
              </thead>
              <tbody>
                  {% for employee in employee_list%}
                    <tr>
                        <td>
                          <div class="d-flex align-items-center">
                            <div class="ms-3">
                              <p class="fw-bold mb-1">{{employee.full_name}}</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <div class="btn-group">
                            <input type="radio" class="btn-check" name="option{{forloop.counter}}" id="option1{{forloop.counter}}" autocomplete="off" value="present"/>
                            <label class="btn btn-primary" for="option1{{forloop.counter}}" onclick="enableInput('in-time{{forloop.counter}}','out-time{{forloop.counter}}')">Present</label>
      
                            <input type="radio" class="btn-check" name="option{{forloop.counter}}" id="option2{{forloop.counter}}" autocomplete="off" value="absent"/>
                            <label class="btn btn-danger" for="option2{{forloop.counter}}" onclick="disableInput('in-time{{forloop.counter}}','out-time{{forloop.counter}}')">Absent</label>
                          </div>
                        </td>
                        <td>
                          <input type="time" name="in-time{{forloop.counter}}"  id="in-time{{forloop.counter}}" class="form-control">
                        </td>
                        <td>
                          <input type="time" name="out-time{{forloop.counter}}" id="out-time{{forloop.counter}}" class="form-control">
                        </td>
                    </tr>
                    {% endfor %}
              </tbody>
            </table><br>
            <div class="float-end">
                <input type="submit" name="submit" class="btn btn-success">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

</section>
<script type="text/javascript">
  function disableInput(firstin, lastOut){
    document.getElementById(firstin).disabled=true;
    document.getElementById(lastout).disabled=true;
  }

  function enableInput(firstin, lastout){
    document.getElementById(firstin).disabled=false;
    document.getElementById(lastout).disabled=false;
  }
</script>
{% endblock %}

b2b_project/hrm/templates/hrm/employee_list.html
{% extends 'shop/admin_base.html' %}

{% block main %}

<section class="section">
      <div class="row">
        <div class="col-lg-12">
         <div class="card">
          <div class="card-header">
            <h5 class="card-title" style="float: left;">Employee List</h5>
            <h5 class="card-title" style="float: right;"><a href="{% url 'hrm:add_employee' %}" class="btn btn-success">Add Employee</a></h5>
          </div>
          
            <div class="card-body">
              
              <!-- Table with stripped rows -->
              <table class="table table-striped datatable">
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Designation</th>
                    <th scope="col">Contact No.</th>
                    <th scope="col">Email</th>
                    <th scope="col">Address</th>
                    <th scope="col">Salary</th>
                    <th scope="col">Joined Date</th>
                    <th scope="col">Remove Employee</th>
                  </tr>
                </thead>
                <tbody>
                {% for employee in employee_list %}
                  <tr>
                    <th scope="row">{{employee.full_name}}</th>
                    <td>{{employee.designation}}</td>
                    <td>{{employee.contact_no}}</td>
                    <td>{{employee.email}}</td>
                    <td>{{employee.address}}</td>
                    <td>{{employee.salary}}</td>
                    <td>{{employee.joined_date}}</td>
                    <td><a href="{% url 'hrm:delete_employee' employee.id %} " onclick="return confirm('Are you sure?')">Delete</a></td>
                  </tr>
                  {% endfor%}
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>
          </div>
        </div>

    </section>

{% endblock %}