b2b_project/api/orders/urls.py
from django.urls import path, include

from rest_framework.routers import SimpleRouter

from .views import OrderViewSet, OrderItemViewSet

router = SimpleRouter()
router.register('', OrderViewSet, basename = 'orders')
router.register('items/', OrderItemViewSet, basename = 'order_items')

urlpatterns = [ 
    path('', include(router.urls)),
]

b2b_project/api/urls.py
from django.urls import path, include

urlpatterns = [
    path('users/', include('user.urls')),
    path('products/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
]

b2b_project/b2b_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('accounts/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
    #path('api/', include('api.urls')),
    path('', include('dashboard.urls')),
    path('', include('shop.urls')),
    path('', include('orders.urls')),
    path('', include('accounting.urls')),
    path('', include('hrm.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

b2b_project/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('admin-dashboard/orders/new/', views.new_orders, name = 'new_orders'),
    path('admin-dashboard/orders/new/<int:order_id>/verify/', views.verify_order, name = 'verify_order'),
    path('admin-dashboard/orders/verified/', views.verified_orders, name = 'verified_orders'),
    path('admin-dashboard/orders/verified/<int:order_id>/mark_on_delivery/', views.mark_order_on_delivery, name = 'mark_on_delivery'),
    path('admin-dashboard/orders/on_delivery/', views.orders_on_delivery, name = 'orders_on_delivery'),
    path('admin-dashboard/orders/completed/', views.completed_orders, name = 'completed_orders'),
    path('admin-dashboard/orders/on_delivery/<int:order_id>/mark_completed/', views.mark_order_completed, name = 'mark_completed'),
    path('admin-dashboard/orders/cancelled/', views.cancelled_orders, name = 'cancelled_orders'),
    path('admin-dashboard/orders/<int:order_id>/invoice/', views.order_invoice, name = 'order_invoice'),   
]

b2b_project/api/orders/models.py
from django.db import models
from user.models import User
from shop.models import Product

class Order(models.Model):
    PAYMENT_CHOICES = [('credit', 'Credit'),('cod', 'Cash on Delivery')]

    ORDER_STATUS_CHOICES = [('unverified', 'Unverified'),('verified','Verified'),
                            ('on_delivery', 'On Delivery'), ('delivered', 'Delivered')]

    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'orders')
    payment_method = models.CharField(max_length = 50, choices = PAYMENT_CHOICES)
    order_status = models.CharField(max_length = 50, choices = ORDER_STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)

    def __str__(self):
        return f"Order {self.id}"
    
    def get_total_cost(self):
        return sum([item.get_cost() for item in self.items.all()])

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete = models.CASCADE, related_name = 'items')
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    #price = models.DecimalField(decimal_places = 2,max_digits = 10)
    quantity = models.PositiveIntegerField(default = 1)

    def __str__(self):
        return f"{self.id}"
    
    def get_cost(self):
        if self.product.discounted_price:
            return self.product.discounted_price * self.quantity
        
        else:
            return self.product.price * self.quantity

b2b_project/orders/models.py
from django.db import models

from user.models import User
from shop.models import Product


class OrderQuerySet(models.QuerySet):
    def get_revenue(self, start_date, end_date):
        return sum([order.get_total_cost() for order in Order.objects.filter(created__range = [start_date, end_date])])


class OrderManager(models.Manager):
    def get_queryset(self):
        return OrderQuerySet(self.model, using=self._db)


class Order(models.Model):
    PAYMENT_CHOICES = [('credit', 'Credit'),('cod', 'Cash on Delivery')]
    ORDER_STATUS_CHOICES = [('unverified', 'Unverified'),
                            ('verified','Verified'),
                            ('on_delivery', 'On Delivery'),
                            ('delivered', 'Delivered'),
                            ('cancelled','Cancelled')]

    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'orders')
    payment_method = models.CharField(max_length = 50, choices = PAYMENT_CHOICES)
    order_status = models.CharField(max_length = 50, choices = ORDER_STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    objects = OrderManager()

    class Meta:
        ordering = ['-created']
        
    def __str__(self):
        return f"Order {self.id}"
    
    def get_total_cost(self):
        return sum([item.get_cost() for item in self.items.all()]) 

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete = models.CASCADE, related_name = 'items')
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    #price = models.DecimalField(decimal_places = 2,max_digits = 10)
    quantity = models.PositiveIntegerField(default = 1)

    def __str__(self):
        return f"{self.id}"
    
    def get_cost(self):
        if self.product.discounted_price:
            return self.product.discounted_price * self.quantity
        
        else:
            return self.product.price * self.quantity

b2b_project/api/orders/views.py
from rest_framework.viewsets import ModelViewSet
from .models import Order, OrderItem
from .serializers import OrderSerializer, OrderItemSerializer

class OrderItemViewSet(ModelViewSet):
    queryset = OrderItem.objects.all()
    serializer_class = OrderItemSerializer

class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

b2b_project/orders/views.py
from django.shortcuts import redirect, render, get_object_or_404

from .models import Order

def new_orders(request):
    new_orders = Order.objects.filter(order_status = 'unverified')
    return render(request,'orders/new_orders.html', {'new_orders':new_orders})

def verify_order(request, order_id):
    order = get_object_or_404(Order, id = order_id)
    order.order_status = 'verified'
    order.save()
    return redirect('orders:new_orders')

def verified_orders(request):
    verified_orders = Order.objects.filter(order_status = 'verified')
    return render(request, 'orders/verified_orders.html', {'verified_orders':verified_orders})

def mark_order_on_delivery(request, order_id):
    order = get_object_or_404(Order, id = order_id)
    order.order_status = 'on_delivery'
    order.save()
    return redirect('orders:verified_orders')

def orders_on_delivery(request):
    on_delivery_orders = Order.objects.filter(order_status = 'on_delivery')
    return render(request, 'orders/on_delivery.html', {'on_delivery_orders':on_delivery_orders})

def mark_order_completed(request, order_id):
    order = get_object_or_404(Order, id = order_id)
    order.order_status = 'delivered'
    order.save()
    return redirect('orders:orders_on_delivery')

def completed_orders(request):
    completed_orders = Order.objects.filter(order_status = 'delivered')
    return render(request,'orders/completed_orders.html', {'completed_orders':completed_orders})

def cancelled_orders(request):
    cancelled_orders = Order.objects.filter(order_status = 'cancelled')
    return render(request,'orders/cancelled_orders.html', {'cancelled_orders':cancelled_orders})

def order_invoice(request, order_id):
    order = get_object_or_404(Order, id = order_id)
    return render(request, 'orders/invoice.html', {'order':order})

b2b_project/orders/templates/orders/cancelled_orders.html
{% extends 'shop/admin_base.html' %}

{% block main %}

<section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Cancelled Orders</h5>
              <!-- Table with stripped rows -->
              <table class="table table-striped datatable">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Product</th>
                    <th scope="col">Price</th>
                    <th scope="col">Qty.</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Total</th>
                    <th scope="col">Invoice</th>
                  </tr>
                </thead>
                <tbody>
                {% for order in cancelled_orders %}
                  <tr>
                    <th scope="row">{{order.id}}</th>
                    <td>{{order.user}}</td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                            <td>{{item.product.name}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                                {% if item.product.discounted_price%}
                                <td>{{item.product.discounted_price}}</td>
                                {% else %}
                                <td>{{item.product.price}}</td>
                                {% endif %}
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                                <td>{{item.quantity}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table>
                        {% for item in order.items.all %}
                            <tr>
                                <td>{{item.get_cost}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>{{order.get_total_cost}}</td>
                    <td><a href="{% url 'orders:order_invoice' order.id %}">view</a></td>
                  </tr>
                  {% endfor%}
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>

{% endblock %}

b2b_project/orders/templates/orders/completed_orders.html
{% extends 'shop/admin_base.html' %}

{% block main %}

<section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Completed Orders</h5>
              <!-- Table with stripped rows -->
              <table class="table table-striped datatable">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Product</th>
                    <th scope="col">Price</th>
                    <th scope="col">Qty.</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Total</th>
                    <th scope="col">Invoice</th>
                  </tr>
                </thead>
                <tbody>
                {% for order in completed_orders %}
                  <tr>
                    <th scope="row">{{order.id}}</th>
                    <td>{{order.user}}</td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                            <td>{{item.product.name}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                                {% if item.product.discounted_price%}
                                <td>{{item.product.discounted_price}}</td>
                                {% else %}
                                <td>{{item.product.price}}</td>
                                {% endif %}
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                                <td>{{item.quantity}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table>
                        {% for item in order.items.all %}
                            <tr>
                                <td>{{item.get_cost}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>{{order.get_total_cost}}</td>
                    <td><a href="{% url 'orders:order_invoice' order.id %}">view</a></td>
                  </tr>
                  {% endfor%}
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>

{% endblock %}

b2b_project/orders/templates/orders/invoice.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<title>Invoice {{order.id}}</title>
		<link
			href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
			rel="stylesheet"
		/>
		<style>
			@media print {
				@page {
					size: A3;
				}
			}
			ul {
				padding: 0;
				margin: 0 0 1rem 0;
				list-style: none;
			}
			body {
				font-family: "Inter", sans-serif;
				margin: 0;
			}
			table {
				width: 100%;
				border-collapse: collapse;
			}
			table,
			table th,
			table td {
				border: 1px solid silver;
			}
			table th,
			table td {
				text-align: right;
				padding: 8px;
			}
			h1,
			h4,
			p {
				margin: 0;
			}

			.container {
				padding: 20px 0;
				width: 1000px;
				max-width: 90%;
				margin: 0 auto;
			}

			.inv-title {
				padding: 10px;
				border: 1px solid silver;
				text-align: center;
				margin-bottom: 30px;
			}

			.inv-logo {
				width: 150px;
				display: block;
				margin: 0 auto;
				margin-bottom: 40px;
			}

			/* header */
			.inv-header {
				display: flex;
				margin-bottom: 20px;
			}
			.inv-header > :nth-child(1) {
				flex: 2;
			}
			.inv-header > :nth-child(2) {
				flex: 1;
			}
			.inv-header h2 {
				font-size: 20px;
				margin: 0 0 0.3rem 0;
			}
			.inv-header ul li {
				font-size: 15px;
				padding: 3px 0;
			}

			/* body */
			.inv-body table th,
			.inv-body table td {
				text-align: left;
			}
			.inv-body {
				margin-bottom: 30px;
			}

			/* footer */
			.inv-footer {
				display: flex;
				flex-direction: row;
			}
			.inv-footer > :nth-child(1) {
				flex: 2;
			}
			.inv-footer > :nth-child(2) {
				flex: 1;
			}
		</style>
	</head>
	<body>
		<div class="container">
			<div class="inv-title">
				<h1>Invoice # {{order.id}}</h1>
			</div>
			<div class="inv-header">
				<div>
					<h2>B2B Project</h2>
					<ul>
						<li>Address</li>
						<li>Country</li>
						<li>+977 111111111 | sample@gmail.com</li>
					</ul>
					<h2>{{order.user.customer.full_name}}</h2>
					<ul>
						<li>{{order.user.customer.address}}</li>
						<li>{{order.user.customer.contact_no}} | {{order.user.email}}</li>
					</ul>
				</div>
				<div>
					<table>
						<tr>
							<th>Issue Date</th>
							<td>{{order.created}}</td>
						</tr>
						<tr>
					</table>
				</div>
			</div>
			<div class="inv-body">
				<table>
					<thead>
						<th>Product</th>
						<th>Quantity</th>
						<th>Price</th>
            <th>Amount</th>
					</thead>
					<tbody>
            {% for item in order.items.all %}
						<tr>
							<td>
								<h4>{{item.product.name}}</h4>
							</td>
							<td>{{item.quantity}}</td>
              {% if not item.product.discounted_price %}
							<td>{{item.product.price}}</td>
              {% else %}
              <td>{{item.product.discounted_price}}</td>
              {% endif %}
              <td>{{item.get_cost}}</td>
						</tr>
            {% endfor %}
					</tbody>
				</table>
			</div>
			<div class="inv-footer">
				<div><!-- required --></div>
				<div>
					<table>
						<tr>
							<th>Sub total</th>
							<td>{{order.get_total_cost}}</td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	</body>
</html>

b2b_project/orders/templates/orders/new_orders.html
{% extends 'shop/admin_base.html' %}

{% block main %}

<section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">New Orders</h5>
              <!-- Table with stripped rows -->
              <table class="table table-striped datatable">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Product</th>
                    <th scope="col">Price</th>
                    <th scope="col">Qty.</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Total</th>
                    <th scpe="col">Payment Method</th>
                    <th scope="col">Status</th>
                    <th scope="col">Invoice</th>
                  </tr>
                </thead>
                <tbody>
                {% for order in new_orders %}
                  <tr>
                    <th scope="row">{{order.id}}</th>
                    <td>{{order.user.customer.full_name}}</td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                            <td>{{item.product.name}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                                {% if item.product.discounted_price%}
                                <td>{{item.product.discounted_price}}</td>
                                {% else %}
                                <td>{{item.product.price}}</td>
                                {% endif %}
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                                <td>{{item.quantity}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table>
                        {% for item in order.items.all %}
                            <tr>
                                <td>{{item.get_cost}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>{{order.get_total_cost}}</td>
                    <td>{{order.payment_method}}</td>
                    <td>Unverified | <a href="{% url 'orders:verify_order' order.id %}">Verify</a></td>
                    <td><a href="{% url 'orders:order_invoice' order.id %}">view</a></td>
                  </tr>
                  {% endfor%}
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>

{% endblock %}

b2b_project/orders/templates/orders/on_delivery.html
{% extends 'shop/admin_base.html' %}

{% block main %}

<section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Orders On Delivery</h5>
              <!-- Table with stripped rows -->
              <table class="table table-striped datatable">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Product</th>
                    <th scope="col">Price</th>
                    <th scope="col">Qty.</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Total</th>
                    <th scope="col">Mark Completed</th>
                    <th scope="col">Invoice</th>
                  </tr>
                </thead>
                <tbody>
                {% for order in on_delivery_orders %}
                  <tr>
                    <th scope="row">{{order.id}}</th>
                    <td>{{order.user}}</td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                            <td>{{item.product.name}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                                {% if item.product.discounted_price%}
                                <td>{{item.product.discounted_price}}</td>
                                {% else %}
                                <td>{{item.product.price}}</td>
                                {% endif %}
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                                <td>{{item.quantity}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table>
                        {% for item in order.items.all %}
                            <tr>
                                <td>{{item.get_cost}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>{{order.get_total_cost}}</td>
                    <td><a href="{% url 'orders:mark_completed' order.id %}">Mark Completed</a></td>
                    <td><a href="{% url 'orders:order_invoice' order.id %}">view</a></td>
                  </tr>
                  {% endfor%}
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>

{% endblock %}

b2b_project/orders/templates/orders/verified_orders.html
{% extends 'shop/admin_base.html' %}

{% block main %}

<section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Verified Orders</h5>
              <!-- Table with stripped rows -->
              <table class="table table-striped datatable">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Product</th>
                    <th scope="col">Price</th>
                    <th scope="col">Qty.</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Total</th>
                    <th scope="col">Mark On Delivery</th>
                    <th scope="col">Invoice</th>
                  </tr>
                </thead>
                <tbody>
                {% for order in verified_orders %}
                  <tr>
                    <th scope="row">{{order.id}}</th>
                    <td>{{order.user}}</td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                            <td>{{item.product.name}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                                {% if item.product.discounted_price%}
                                <td>{{item.product.discounted_price}}</td>
                                {% else %}
                                <td>{{item.product.price}}</td>
                                {% endif %}
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table class="table table-borderless">
                        {% for item in order.items.all %}
                            <tr>
                                <td>{{item.quantity}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>
                        <table>
                        {% for item in order.items.all %}
                            <tr>
                                <td>{{item.get_cost}}</td>
                            </tr>
                        {% endfor%}
                        </table>
                    </td>
                    <td>{{order.get_total_cost}}</td>
                    <td><a href="{% url 'orders:mark_on_delivery' order.id %}"> Mark On Delivery</a></td>
                    <td><a href="{% url 'orders:order_invoice' order.id %}">view</a></td>
                  </tr>
                  {% endfor%}
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>

{% endblock %}